kind = "web"
previewPath = "/"
title = "SkyXpress"
version = "1.0.0"
id = "artifacts/skyxpress"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20181

[services.development]
run = "pnpm --filter @workspace/skyxpress run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/skyxpress", "run", "build" ]
serve = "static"
publicDir = "artifacts/skyxpress/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20181"
BASE_PATH = "/"
